spring:
  application:
    name: reference-manager-service

  datasource:
    url: jdbc:mysql://localhost:3306/reference_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Liquibase kullanacağız
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:com.flightmanagement.referencemanager.event.ReferenceEvent

server:
  port: 8081

jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000  # 24 hours

logging:
  level:
    com.flightmanagement: DEBUG